global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'apisix'
    metrics_path: /apisix/prometheus/metrics
    static_configs:
      - targets: ['apisix:9091']
  - job_name: 'users'
    scheme: https
    metrics_path: /metrics
    tls_config:
      cert_file: /certs/prometheus.crt
      key_file: /certs/prometheus.key
      ca_file: /certs/ca.crt
    static_configs:
      - targets: ['users:5000']

  - job_name: 'products'
    scheme: https
    metrics_path: /metrics
    tls_config:
      cert_file: /certs/prometheus.crt
      key_file: /certs/prometheus.key
      ca_file: /certs/ca.crt
    static_configs:
      - targets: ['products:5000']

  - job_name: 'orders'
    scheme: https
    metrics_path: /metrics
    tls_config:
      cert_file: /certs/prometheus.crt
      key_file: /certs/prometheus.key
      ca_file: /certs/ca.crt
    static_configs:
      - targets: ['orders:5000']

  - job_name: 'auth'
    scheme: https
    metrics_path: /metrics
    tls_config:
      cert_file: /certs/prometheus.crt
      key_file: /certs/prometheus.key
      ca_file: /certs/ca.crt
    static_configs:
      - targets: ['auth:5000']
